# Generated by Django 5.0.14 on 2025-08-29 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('volume_horaire', models.PositiveIntegerField(default=0)),
                ('classes', models.ManyToManyField(related_name='cours', through='scolarite.Coefficient', to='administration.classe')),
            ],
        ),
        migrations.AddField(
            model_name='coefficient',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolarite.cours'),
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.eleve')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.etablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('ancien_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='utilisateurs.eleve')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='administration.periode')),
            ],
        ),
        migrations.CreateModel(
            name='Tranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField()),
                ('mode_paiement', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='scolarite.inscription')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='coefficient',
            unique_together={('classe', 'cours')},
        ),
    ]
