# Generated by Django 5.2.6 on 2025-09-13 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_initial'),
        ('scolarite', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.eleve'),
        ),
        migrations.AddField(
            model_name='demande',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.etablissement'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='ancien_eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='utilisateurs.ancieneleve'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='administration.periode'),
        ),
        migrations.AddField(
            model_name='tranche',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='scolarite.inscription'),
        ),
        migrations.AlterUniqueTogether(
            name='coefficient',
            unique_together={('classe', 'cours')},
        ),
    ]
