# Generated by Django 5.2.6 on 2025-09-13 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscriptionetablissement',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to='utilisateurs.chefetablissement'),
        ),
        migrations.AddField(
            model_name='souscriptionetablissement',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to='administration.etablissement'),
        ),
    ]
