# Generated by Django 5.0.14 on 2025-08-29 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('scolarite', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_publication', models.DateField()),
                ('date_devoir', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('note_max', models.FloatField(default=20)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs', to='scolarite.cours')),
            ],
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=20)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='administration.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField(blank=True, null=True)),
                ('remarque', models.TextField(blank=True)),
                ('bareme', models.FloatField(default=20)),
                ('ancien_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='utilisateurs.ancieneleve')),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='pedagogie.devoir')),
            ],
            options={
                'unique_together': {('devoir', 'ancien_eleve')},
            },
        ),
        migrations.AddField(
            model_name='devoir',
            name='eleves',
            field=models.ManyToManyField(related_name='devoirs', through='pedagogie.Note', to='utilisateurs.ancieneleve'),
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=20)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedagogie_periodes', to='administration.etablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances', to='scolarite.cours')),
                ('devoir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='pedagogie.devoir')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances', to='utilisateurs.enseignant')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances', to='administration.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jours', models.CharField(max_length=20)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('emploi_du_temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='pedagogie.emploidutemps')),
                ('seance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux', to='pedagogie.seance')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=200)),
                ('justifier', models.BooleanField(default=False)),
                ('ancien_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='utilisateurs.ancieneleve')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='pedagogie.seance')),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimestres', to='pedagogie.periode')),
            ],
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention', models.CharField(blank=True, max_length=50)),
                ('date_creation', models.DateField()),
                ('ancien_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='utilisateurs.ancieneleve')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='pedagogie.trimestre')),
            ],
        ),
    ]
