# Generated by Django 5.2.6 on 2025-09-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=200)),
                ('justifier', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_publication', models.DateField()),
                ('date_devoir', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('note_max', models.FloatField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField(blank=True, null=True)),
                ('remarque', models.TextField(blank=True)),
                ('bareme', models.FloatField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pourcentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField(help_text='Valeur du pourcentage (ex: 30 pour 30%)')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(default='2024-2025', max_length=20)),
                ('heures_par_semaine', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('annule', 'Annulé')], default='actif', max_length=20)),
                ('jours', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('heure_debut', models.TimeField()),
                ('duree', models.PositiveIntegerField(default=60)),
                ('type', models.CharField(choices=[('Cours', 'Cours'), ('TD', 'TD'), ('TP', 'TP')], max_length=50)),
                ('status', models.CharField(choices=[('Planifie', 'Planifiée'), ('Effectue', 'Effectuée'), ('Annule', 'Annulée')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
    ]
