# Generated by Django 5.2.6 on 2025-09-04 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_initial'),
        ('pedagogie', '0001_initial'),
        ('scolarite', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='ancien_eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='utilisateurs.ancieneleve'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='ancien_eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='utilisateurs.ancieneleve'),
        ),
        migrations.AddField(
            model_name='creneau',
            name='devoir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux', to='pedagogie.devoir'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='administration.salle'),
        ),
        migrations.AddField(
            model_name='creneau',
            name='emploi_du_temps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='pedagogie.emploidutemps'),
        ),
        migrations.AddField(
            model_name='enseignement',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='scolarite.cours'),
        ),
        migrations.AddField(
            model_name='enseignement',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='utilisateurs.enseignant'),
        ),
        migrations.AddField(
            model_name='enseignement',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='administration.salle'),
        ),
        migrations.AddField(
            model_name='note',
            name='ancien_eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='utilisateurs.ancieneleve'),
        ),
        migrations.AddField(
            model_name='note',
            name='devoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='pedagogie.devoir'),
        ),
        migrations.AddField(
            model_name='devoir',
            name='eleves',
            field=models.ManyToManyField(related_name='devoirs', through='pedagogie.Note', to='utilisateurs.ancieneleve'),
        ),
        migrations.AddField(
            model_name='seance',
            name='enseignement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='pedagogie.enseignement'),
        ),
        migrations.AddField(
            model_name='creneau',
            name='seance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux', to='pedagogie.seance'),
        ),
        migrations.AddField(
            model_name='absence',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='pedagogie.seance'),
        ),
        migrations.AddField(
            model_name='trimestre',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimestres', to='administration.periode'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='trimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='pedagogie.trimestre'),
        ),
        migrations.AlterUniqueTogether(
            name='enseignement',
            unique_together={('enseignant', 'cours', 'salle', 'annee_scolaire')},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('devoir', 'ancien_eleve')},
        ),
        migrations.AlterUniqueTogether(
            name='seance',
            unique_together={('enseignement', 'date', 'heure_debut')},
        ),
    ]
