# Generated by Django 5.2.6 on 2025-09-13 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_initial'),
        ('pedagogie', '0001_initial'),
        ('scolarite', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='ancien_eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='utilisateurs.ancieneleve'),
        ),
        migrations.AddField(
            model_name='devoir',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs', to='scolarite.cours'),
        ),
        migrations.AddField(
            model_name='note',
            name='ancien_eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='utilisateurs.ancieneleve'),
        ),
        migrations.AddField(
            model_name='note',
            name='devoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='pedagogie.devoir'),
        ),
        migrations.AddField(
            model_name='devoir',
            name='pourcentage',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, related_name='devoirs', to='pedagogie.pourcentage'),
        ),
        migrations.AddField(
            model_name='seance',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='scolarite.cours'),
        ),
        migrations.AddField(
            model_name='seance',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='utilisateurs.enseignant'),
        ),
        migrations.AddField(
            model_name='seance',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='administration.salle'),
        ),
        migrations.AddField(
            model_name='devoir',
            name='seance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devoirs', to='pedagogie.seance'),
        ),
        migrations.AddField(
            model_name='absence',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='pedagogie.seance'),
        ),
        migrations.AddField(
            model_name='trimestre',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimestres', to='administration.periode'),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('devoir', 'ancien_eleve')},
        ),
        migrations.AlterUniqueTogether(
            name='seance',
            unique_together={('enseignant', 'cours', 'salle', 'annee_scolaire', 'jours', 'heure_debut')},
        ),
    ]
