# Generated by Django 5.2.6 on 2025-09-15 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='pourcentage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs', to='pedagogie.pourcentage'),
        ),
    ]
