# Generated by Django 5.2.6 on 2025-09-15 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0003_alter_devoir_pourcentage'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='note',
            name='trimestre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='pedagogie.trimestre'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('devoir', 'ancien_eleve', 'trimestre')},
        ),
    ]
