# Generated by Django 5.0.14 on 2025-08-29 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('mot_passe', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.BooleanField(default=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Caissier',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
                ('date_embauche', models.DateField()),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='Censeur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
                ('date_embauche', models.DateField()),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='ChefEtablissement',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
                ('date_embauche', models.DateField()),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
                ('date_inscription', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='eleves_photos/')),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('specialite', models.CharField(blank=True, max_length=100)),
                ('date_embauche', models.DateField()),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
                ('lien_parent', models.CharField(blank=True, max_length=50)),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='AncienEleve',
            fields=[
                ('eleve_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.eleve')),
                ('matricule', models.CharField(blank=True, max_length=50)),
                ('niveau', models.CharField(blank=True, max_length=50)),
            ],
            bases=('utilisateurs.eleve',),
        ),
    ]
