# Generated by Django 5.2.6 on 2025-09-13 10:28

import django.db.models.deletion
import django.utils.timezone
import utilisateurs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('parent', 'Parent'), ('eleve', 'Élève'), ('enseignant', 'Enseignant'), ('chef', 'Chef d’établissement'), ('censeur', 'Censeur'), ('caissier', 'Caissier')], max_length=20)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.BooleanField(default=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', utilisateurs.models.UtilisateurManager()),
            ],
        ),
        migrations.CreateModel(
            name='Caissier',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_embauche', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('utilisateurs.utilisateur',),
            managers=[
                ('objects', utilisateurs.models.UtilisateurManager()),
            ],
        ),
        migrations.CreateModel(
            name='Censeur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_embauche', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('utilisateurs.utilisateur',),
            managers=[
                ('objects', utilisateurs.models.UtilisateurManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChefEtablissement',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_embauche', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('utilisateurs.utilisateur',),
            managers=[
                ('objects', utilisateurs.models.UtilisateurManager()),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_inscription', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='eleves_photos/')),
            ],
            options={
                'abstract': False,
            },
            bases=('utilisateurs.utilisateur',),
            managers=[
                ('objects', utilisateurs.models.UtilisateurManager()),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('specialite', models.CharField(blank=True, choices=[('math', 'Mathématiques'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('francais', 'Français'), ('anglais', 'Anglais')], max_length=50)),
                ('date_embauche', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('utilisateurs.utilisateur',),
            managers=[
                ('objects', utilisateurs.models.UtilisateurManager()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lien_parent', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('utilisateurs.utilisateur',),
            managers=[
                ('objects', utilisateurs.models.UtilisateurManager()),
            ],
        ),
        migrations.CreateModel(
            name='AncienEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50)),
                ('niveau', models.CharField(blank=True, max_length=50)),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.salle')),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.eleve')),
            ],
        ),
    ]
