# Generated by Django 5.2.6 on 2025-09-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SouscriptionParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_souscription', models.DateField()),
                ('matricule', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
