# Generated by Django 5.2.6 on 2025-09-13 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscriptionparent',
            name='ancien_eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions_parent', to='utilisateurs.ancieneleve'),
        ),
        migrations.AddField(
            model_name='souscriptionparent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions_parent', to='utilisateurs.parent'),
        ),
        migrations.AlterUniqueTogether(
            name='souscriptionparent',
            unique_together={('parent', 'ancien_eleve')},
        ),
    ]
