# Generated by Django 5.2.6 on 2025-09-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Notification', max_length=100)),
                ('message', models.TextField()),
                ('date_envoie', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('devoir', 'Devoir'), ('absence', 'Absence'), ('paiement', 'Paiement'), ('general', 'Général'), ('inscription', 'Inscription')], default='general', max_length=20)),
            ],
        ),
    ]
