# Generated by Django 5.0.14 on 2025-08-29 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_envoie', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('titre', models.CharField(blank=True, max_length=100)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='utilisateurs.utilisateur')),
            ],
        ),
    ]
